version: "3.8"
services:
  mysql:
    build:
      context: mysql
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWD}
    container_name: ${PROJECT_NAME}-mysql
    image: ${PROJECT_NAME}/mysql:5.7
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=128M
    volumes:
      - ${VOLUMES_MYSQL_LOCAL_PATH}:/var/lib/mysql
    ports:
      - ${MYSQL_PORT}:3306
    networks:
      app_net:
        ipv4_address: 172.16.${SUBNET_NUM}.11
  redis:
    image: redis:6.0
    container_name: ${PROJECT_NAME}-redis
    command: redis-server --requirepass ${REDIS_PASSWD}
    volumes:
      - ${VOLUMES_REDIS_LOCAL_PATH}:/data
    networks:
      app_net:
        ipv4_address: 172.16.${SUBNET_NUM}.12
    ports:
      - ${REDIS_PORT}:6379
  eu-admin:
    build:
      context: ../
      dockerfile: ./env/eu-admin/Dockerfile
    image: ${PROJECT_NAME}/eu-admin:${APP_VERSION}
    container_name: ${PROJECT_NAME}-admin
    environment:
      SPRING_PROFILE: ${APP_PROFILE}
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWD}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWD}
    ports:
      - ${EU_ADMIN_PORT}:8000
    volumes:
      - ${VOLUMES_EU_ADMIN_LOCAL_PATH}:/home/eu/logs
    depends_on:
      - mysql
      - redis
    networks:
      app_net:
        ipv4_address: 172.16.${SUBNET_NUM}.13

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.${SUBNET_NUM}.0/24